add instrumentation pkg of confluent-kafka-go/kafka/v2
signalfx/splunk-otel-go pull request #2301
Opened 2023-06-13 03:18 UTC by eaglerayp

Add the splunkkafkav2 package to provide support for confluent-kafka-go/kafka/v2 while maintaining compatibility.

2023-06-14 07:50 UTC, pellared reviewed
Can you please sign the [Splunk Contributor License Agreement (CLA)](https://www.splunk.com/en_us/form/contributions.html)?

PS. Please let us know when you do it.

2023-06-14 07:50 UTC, pellared commented on instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/splunkkafkav2/README.md
Can you please change the directory structure from `instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/splunkkafkav2` to `instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka`?

2023-06-14 10:09 UTC, pellared commented
The GitHub workflows are failing e.g.:
- https://github.com/signalfx/splunk-otel-go/actions/runs/5250959820/jobs/9515552525?pr=2301
- https://github.com/signalfx/splunk-otel-go/actions/runs/5250959820/jobs/9515551730?pr=2301

I guess you need to update the `go.mod` and `go.sum` files.

2023-06-15 08:02 UTC, eaglerayp commented on instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/splunkkafkav2/README.md
updated.

2023-06-15 08:02 UTC, eaglerayp commented
updated above errors and changes.
CLA also signed.

2023-06-20 06:41 UTC, pellared reviewed
@MrAlias PTAL. Do you think that we should support both `v1` and `v2` of [`confluent-kafka-go`](https://github.com/confluentinc/confluent-kafka-go)?

2023-06-20 06:41 UTC, pellared commented on CHANGELOG.md
> +- Add a new package called splunkkafkav2 to the instrumentation package of confluent-kafka-go v2.
```suggestion
### Added

- Add the `github.com/signalfx/splunk-otel-go/instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka` instrumentation for the `github.com/confluentinc/confluent-kafka-go/kafka/v2` package. (#2301)
```

2023-06-20 07:03 UTC, pellared commented
Build errors https://github.com/signalfx/splunk-otel-go/actions/runs/5319398623/jobs/9631849109?pr=2301:

```
Error: doc.go:15:1: package-comments: package comment should be of the form "Package splunkkafka ..." (revive)
// package splunkkafka provides functions to trace the
// github.com/confluentinc/confluent-kafka-go/kafka package.
Error: consumer.go:108:46: SA1019: c.Events is deprecated: Events (channel based consumer) is deprecated in favour of Poll(). (staticcheck)
	wrapped.events = wrapped.traceEventsChannel(c.Events())
	                                            ^
Error: producer.go:70:55: SA1019: p.ProduceChannel is deprecated: ProduceChannel (channel based producer) is deprecated in favour of Produce(). Flush() and Len() are not guaranteed to be reliable with ProduceChannel. (staticcheck)
	wrapped.produceChannel = wrapped.traceProduceChannel(p.ProduceChannel())
	                                                     ^
Error: consumer_test.go:151:3: SA1019: c.Consumer.Events is deprecated: Events (channel based consumer) is deprecated in favour of Poll(). (staticcheck)
		c.Consumer.Events() <- msg
		^
Error: consumer_test.go:[198](https://github.com/signalfx/splunk-otel-go/actions/runs/5319398623/jobs/9631849109?pr=2301#step:4:199):3: SA1019: c.Consumer.Events is deprecated: Events (channel based consumer) is deprecated in favour of Poll(). (staticcheck)
		c.Consumer.Events() <- &kafka.Message{
```

2023-06-20 07:22 UTC, pellared commented
> In my opinion, the Splunk instrumentation library still needs to support the deprecated method for compatibility. What are your thoughts on this? @pellared

I agree with you. In order to fix the issues it would be good enough to add comments like `//nolint: staticcheck // Ensure backwards support of deprecated API.`.

2023-06-20 07:34 UTC, eaglerayp commented
updated for build error (linter issues)

2023-06-26 01:53 UTC, eaglerayp commented
@pellared  do we have any update on this?

2023-06-26 06:23 UTC, pellared commented
> @pellared do we have any update on this?

I need a few days to discuss https://github.com/signalfx/splunk-otel-go/pull/2301#pullrequestreview-1487415830

2023-06-29 10:41 UTC, pellared commented on instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka/README.md
> +[github.com/confluentinc/confluent-kafka-go/kafka](https://github.com/confluentinc/confluent-kafka-go)
```suggestion
[github.com/confluentinc/confluent-kafka-go/v2/kafka (https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/v2/kafka)
```

2023-06-29 10:41 UTC, pellared commented on instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka/README.md
> +of github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka. Similar to the
```suggestion
Similar to the
```

The first sentence is redundant.

2023-06-29 10:57 UTC, pellared approved these changes

2023-06-29 11:11 UTC, pellared requested changes
I just noticed that the path was wrong in the docs.

Can you please reorganize the repo and move `github.com/signalfx/splunk-otel-go/instrumentation/github.com/confluentinc/confluent-kafka-go/kafka/v2/splunkkafka` -> `github.com/signalfx/splunk-otel-go/instrumentation/github.com/confluentinc/confluent-kafka-go/v2/kafka/splunkkafka`? Sorry that I missed it initially.

2023-06-29 11:11 UTC, pellared commented on CHANGELOG.md
> +  package. (#2301)
```suggestion
- Add the `github.com/signalfx/splunk-otel-go/instrumentation/github.com/confluentinc/confluent-kafka-go/v2/kafka/splunkkafka`
  instrumentation for the `github.com/confluentinc/confluent-kafka-go/v2/kafka`
  package. (#2301)
```

2023-06-30 04:49 UTC, eaglerayp commented on CHANGELOG.md
> +  package. (#2301)
updated

2023-06-30 06:15 UTC, pellared approved these changes

2023-07-02 08:52 UTC, eaglerayp commented
Do we still miss anything?

2023-07-14 15:29 UTC, merged