Restructure docs
signalfx/splunk-otel-go pull request #853
Opened 2022-04-08 12:18 UTC by pellared

Addresses https://github.com/signalfx/splunk-otel-go/pull/731#discussion_r843795147

2022-04-08 17:29 UTC, theletterf requested changes

2022-04-08 17:29 UTC, theletterf commented on CONTRIBUTING.md
> +The repository's "unofficial" documentation is kept under [docs](./docs)
```suggestion
The draft documentation of the repository is under [docs](./docs).
```

2022-04-08 17:29 UTC, theletterf commented on CONTRIBUTING.md
> +directory.
```suggestion
```

2022-04-08 17:29 UTC, theletterf commented on README.md
> +multiple packages that instruments your Go
```suggestion
multiple packages that instrument your Go
```

2022-04-08 17:29 UTC, theletterf commented on README.md
> +Please read [CONTRIBUTING.md](CONTRIBUTING.md)
```suggestion
Read [CONTRIBUTING.md](CONTRIBUTING.md)
```

2022-04-08 17:29 UTC, theletterf commented on docs/README.md
> +# Unofficial documentation
```suggestion
# Draft documentation
```

2022-04-08 17:29 UTC, theletterf commented on docs/README.md
> +# Unofficial documentation
@pellared We don't give a special name to GH docs in other repos, but it's interesting to think of one. I'd rather go with "Draft", as "Unofficial" gives the idea that this is not Splunk's effort, while it is. We do support these docs, too.

2022-04-10 16:29 UTC, theletterf approved these changes

2022-04-20 11:35 UTC, pellared commented
@MrAlias PTAL

2022-05-04 06:55 UTC, pellared commented
> The RELEASING.md file was moved to the docs directory. It is developer documentation for the project not intended for the user. It should remain in the top level.

How about moving it to `docs/internal` as we did with @theletterf blessing [here](https://github.com/signalfx/signalfx-dotnet-tracing/tree/main/docs/internal) and [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/docs)?

2022-05-04 18:12 UTC, MrAlias approved these changes

2022-05-04 18:12 UTC, merged